name: Publish Entities Nuget Packages

on:
  push:
    branches: [ master ]
    paths:
      - 'Entities/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build Entities/Entities.csproj -c Release
    - name: Pack nugets
      run: dotnet pack Entities/Entities.csproj -c Release --no-build --output Entities/
    - name: Push to NuGet
      run: dotnet nuget push "Entities/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
