name: Publish Messages Nuget Packages

on:
  push:
    branches: [ master ]
    paths:
      - 'Messages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build Messages/Messages.csproj -c Release
      - name: Pack nugets
        run: dotnet pack Messages/Messages.csproj -c Release --no-build --output Messages/
      - name: Push to NuGet
        run: dotnet nuget push "Messages/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json